#!/usr/bin/env python3
"""export_skills.py — build the portable skills/ bundle from the source of truth.

The single source of truth is `.claude/skills/` (SKILL.md + scripts + references-as-symlinks into docs/). This
script dereferences those symlinks into a self-contained `skills/` folder that another project can copy.

Run:  python3 tools/export_skills.py

Do not edit `skills/` by hand — regenerate it here. A test (tests/test_skills_export.py) asserts the committed
`skills/` matches a fresh export, so drift is caught, not hand-synced.
"""
from __future__ import annotations

import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / ".claude" / "skills"
DEST = REPO / "skills"

# workflow-design's references/assets are symlinks into docs/ — dereference them to real files.
DEREF = ("references", "assets")
# The general standards and bootstrap are single-file skills.
SINGLE_FILE_SKILLS = ("requirement-check", "meaningful-names", "bootstrap")

README = """# Ancient Games — skills bundle

Four skills, self-contained so another project can copy them in and use them. No symlinks — everything here is a
real file. **Generated by `tools/export_skills.py` — do not edit by hand.**

| skill | what it does | triggers on |
|---|---|---|
| `workflow-design` | the method half of the Ancient Games: turn a task into a designed workflow (or decide none is needed) | designing a workflow / deciding none is needed |
| `requirement-check` | evaluate a rule / requirement / threshold against the eight questions | a stated rule or requirement |
| `meaningful-names` | the clean-code standard for naming (one word, one job) | naming / a name that does several jobs |
| `bootstrap` | generate a project's `AGENTS.md` + `orchestration.mdc` from the Ancient Games | a project wants to work the Ancient Games way |

`workflow-design` is the whole method as one folder: `SKILL.md` (the trigger and the method as eight steps),
`references/` (`method.md` with the full method and its reasons, plus `task-types.md` — the defaults per task type —
`executor-kinds.md`, `feedback-templates.md`), `assets/templates/` (nine templates, from `prompt-file.md` to
`blueprint.md`) and `scripts/` (the enforcing tools: `design_gate.py` checks a design against the table,
`dispatch.py` runs a plan with the timers and the pass-back check, and the rest are the readiness, result-file,
quote, workload, runlog and harvest checks).

## Start here

- **Adopting the style in a project** — paste the block from `BOOTSTRAP_PROMPT.md` into a fresh agent session in
  that project, with a local path to the Ancient Games repo filled in. It installs all four skills and writes that
  project's `AGENTS.md` + root `orchestration.mdc`. Read `bootstrap/SKILL.md` for the input sources, required output
  content and completion checks. Missing blueprint decisions produce drafts and blocked work, not guessed values.
- **Designing a workflow** — install `workflow-design` and load the skill. Read `references/method.md` once before
  your first design.

## Use it

For bootstrap, install **all four sibling folders**: `workflow-design`, `requirement-check`, `meaningful-names`,
and `bootstrap`. The examples below show individual copies, not a complete bootstrap install.
Create the skill root first. Inspect existing folders/symlinks before copying; reuse identical installs and obtain
authorization before replacing different ones. Do not merge copies or write through destination symlinks.
Copy each absent folder into the skill root your harness scans:

```
cp -r skills/workflow-design  ~/.claude/skills/workflow-design     # Claude Code
cp -r skills/workflow-design  ~/.agents/skills/workflow-design     # DeepSeek Harness / Codex
cp -r skills/bootstrap        ~/.claude/skills/bootstrap           # requires the other three sibling skills
```

`requirement-check` and `meaningful-names` are general standards — install them anywhere. `workflow-design` and
`bootstrap` are the Ancient Games framework's method half.
The bundle's README and prompt are documentation, not installable skills. Verify installed references resolve;
read a skill's `SKILL.md` directly if the harness has no loading command. Record the actual install locations in
the generated project instructions.

## What adoption writes

`AGENTS.md` identifies the project, its blueprint, working rules and actual test/build commands. If an existing
file already holds the canonical instructions, preserve that arrangement and make `AGENTS.md` a pointer to it.
The canonical instructions explicitly say to read `orchestration.mdc` before work in every session; a `.mdc`
filename alone does not establish that read. `orchestration.mdc` instantiates the project's task mappings, checks,
bounded loops, referee decisions, worker returns and verified handoffs, with installed-skill references for details.

The four standing rules are the exception to one-copy guidance. Copy each verbatim into both generated files
(the canonical target if `AGENTS.md` is a pointer), with unfamiliar terms glossed separately:

- **Every field has one writer** — a return template is the worker's; a verdict is the human's. Name who fills it.
- **Evidence lives in the project** (`runs/<run-id>/` by default, SHOULD — a written reason may override); scratch in `/tmp` is fine, the refer-back artifact must not stay there.
- **A workflow is a checked sequence** — each step's result is verified, then becomes the next step's input. Not a
  DAG for its own sake.
- **The knowledge graph is declared** — each piece's needs and outputs, and what each must not see.

A run id names one run's folder. A knowledge graph declares each work piece's needs, outputs and withheld context;
it does not require a graph database. DAG means directed acyclic graph. A checked sequence verifies each result
before a dependent step uses it. Workers write their returns; verifiers write separate judgments; humans write
their approval decisions. State holds progress/results with one writer at a time; evidence is saved proof.

## What travels, and what does not

- Project paths such as `docs/blueprint/`, `docs/research/` and `runs/<run-id>/` are relative to the adopting
  project; verify them there, or mark them planned with who creates them and when. Not every `docs/` reference
  in the source material is portable. Installed-skill `references/`, `assets/` and `scripts/` paths resolve under
  that skill's actual installed folder, not the project's root.
- Paths under `ancient_games/`, `docs/DISPATCHER_DESIGN.md`, `docs/TASK_TYPES_LEDGER.md` and `code_graph/` name the
  Ancient Games repo itself — those only make sense inside this repository.
- The **referee** does not travel: `ancient_games/` and its `SPEC.md` are not in this bundle. A project that adopts
  the skills gets the five referee stages (Gate · Guard · Corroborate · Filter · Prove) as written rules, with the
  framework's working numbers. Executable-referee adoption is separate from bootstrap and requires its code,
  dependencies and contract documents; the skills alone do not install or verify it.
- Defaults such as the 3-step rule, attempt limits and cost figures carry their source's evidence status
  (`n=0`: unmeasured; `n=1`: one trial). Evidence from this repository is not verification in the adopting project.
  Keep the source, unit and status when carrying a default over. The ledger for measured replacements
  (`docs/TASK_TYPES_LEDGER.md`) does not travel either, so the adopting project keeps its own.
- `scripts/design_gate.py` finds `TASK_TYPES.md` relative to its own folder, so it works in the bundle too.
"""


def copy_deref(src: Path, dst: Path) -> None:
    """Copy a file/dir, dereferencing symlinks, skipping __pycache__ and .pyc."""
    if src.is_symlink():
        src = src.resolve()
    if src.is_dir():
        dst.mkdir(parents=True, exist_ok=True)
        for child in src.iterdir():
            if child.name == "__pycache__" or child.suffix == ".pyc":
                continue
            copy_deref(child, dst / child.name)
    else:
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)


def main() -> int:
    if DEST.exists():
        shutil.rmtree(DEST)
    DEST.mkdir(parents=True)

    # workflow-design: full skill
    wd_src, wd_dst = SRC / "workflow-design", DEST / "workflow-design"
    for child in wd_src.iterdir():
        if child.name == "__pycache__":
            continue
        copy_deref(child, wd_dst / child.name)

    # Single-file skills.
    for name in SINGLE_FILE_SKILLS:
        copy_deref(SRC / name / "SKILL.md", DEST / name / "SKILL.md")

    shutil.copy2(REPO / "BOOTSTRAP_PROMPT.md", DEST / "BOOTSTRAP_PROMPT.md")
    (DEST / "README.md").write_text(README)

    # sanity: no symlinks remain
    links = [p for p in DEST.rglob("*") if p.is_symlink()]
    if links:
        print(f"ERROR: symlinks remain in the bundle: {links}")
        return 1
    print(f"exported skills/ — workflow-design + {', '.join(SINGLE_FILE_SKILLS)}, no symlinks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
