#!/usr/bin/env python3
"""export_skills.py — build the portable skills/ bundle from the source of truth.

The single source of truth is `.claude/skills/` (SKILL.md + scripts + references-as-symlinks into docs/). This
script dereferences those symlinks into a self-contained `skills/` folder that another project can copy.

Run:  python3 tools/export_skills.py

Do not edit `skills/` by hand — regenerate it here. A test (tests/test_skills_export.py) asserts the committed
`skills/` matches a fresh export, so drift is caught, not hand-synced.
"""
from __future__ import annotations

import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / ".claude" / "skills"
DEST = REPO / "skills"

# workflow-design's references/assets are symlinks into docs/ — dereference them to real files.
DEREF = ("references", "assets")
# the two general standards are single-file skills
SINGLE_FILE_SKILLS = ("requirement-check", "meaningful-names")

README = """# Ancient Games — skills bundle

Three skills, self-contained so another project can drop them in and use them. No symlinks — everything here is a
real file. **Generated by `tools/export_skills.py` — do not edit by hand.**

| skill | what it does | triggers on |
|---|---|---|
| `workflow-design` | the method half of the Ancient Games: turn a task into a designed workflow (or decide none is needed) | designing a workflow / deciding none is needed |
| `requirement-check` | evaluate a rule / requirement / threshold against the eight questions | a stated rule or requirement |
| `meaningful-names` | the clean-code standard for naming (one word, one job) | naming / a name that does several jobs |

## Use it

Copy a skill's folder into one of the skill roots the tool scans:

```
cp -r skills/workflow-design  ~/.claude/skills/     # Claude Code
cp -r skills/workflow-design  ~/.agents/skills/     # DeepSeek Harness / Codex
```

`requirement-check` and `meaningful-names` are general standards — install them anywhere. `workflow-design` is the
member of the Ancient Games framework (method + referee + knowledge).

## Notes

- Paths under `docs/` (blueprint, research) and `runs/<id>/` name the *installing project's* own folders, so they
  read correctly in any project.
- Paths under `ancient_games/`, `docs/DISPATCHER_DESIGN.md`, `docs/TASK_TYPES_LEDGER.md` and `code_graph/` name the
  Ancient Games repo itself — those only make sense inside this repository.
- `scripts/design_gate.py` finds `TASK_TYPES.md` relative to its own folder, so it works in the bundle too.
"""


def copy_deref(src: Path, dst: Path) -> None:
    """Copy a file/dir, dereferencing symlinks, skipping __pycache__ and .pyc."""
    if src.is_symlink():
        src = src.resolve()
    if src.is_dir():
        dst.mkdir(parents=True, exist_ok=True)
        for child in src.iterdir():
            if child.name == "__pycache__" or child.suffix == ".pyc":
                continue
            copy_deref(child, dst / child.name)
    else:
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)


def main() -> int:
    if DEST.exists():
        shutil.rmtree(DEST)
    DEST.mkdir(parents=True)

    # workflow-design: full skill
    wd_src, wd_dst = SRC / "workflow-design", DEST / "workflow-design"
    for child in wd_src.iterdir():
        if child.name == "__pycache__":
            continue
        copy_deref(child, wd_dst / child.name)

    # the two single-file skills
    for name in SINGLE_FILE_SKILLS:
        copy_deref(SRC / name / "SKILL.md", DEST / name / "SKILL.md")

    (DEST / "README.md").write_text(README)

    # sanity: no symlinks remain
    links = [p for p in DEST.rglob("*") if p.is_symlink()]
    if links:
        print(f"ERROR: symlinks remain in the bundle: {links}")
        return 1
    print(f"exported skills/ — workflow-design + {', '.join(SINGLE_FILE_SKILLS)}, no symlinks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
